/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTestIndexRouteImport } from './routes/_layout/test/index'
import { Route as LayoutQuestionsIndexRouteImport } from './routes/_layout/questions/index'
import { Route as LayoutTrainSectionIdRouteImport } from './routes/_layout/train/$sectionId'
import { Route as LayoutQuestionsSectionIdRouteImport } from './routes/_layout/questions/$sectionId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTestIndexRoute = LayoutTestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuestionsIndexRoute = LayoutQuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTrainSectionIdRoute = LayoutTrainSectionIdRouteImport.update({
  id: '/train/$sectionId',
  path: '/train/$sectionId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuestionsSectionIdRoute =
  LayoutQuestionsSectionIdRouteImport.update({
    id: '/questions/$sectionId',
    path: '/questions/$sectionId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/questions/$sectionId': typeof LayoutQuestionsSectionIdRoute
  '/train/$sectionId': typeof LayoutTrainSectionIdRoute
  '/questions/': typeof LayoutQuestionsIndexRoute
  '/test/': typeof LayoutTestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/questions/$sectionId': typeof LayoutQuestionsSectionIdRoute
  '/train/$sectionId': typeof LayoutTrainSectionIdRoute
  '/questions': typeof LayoutQuestionsIndexRoute
  '/test': typeof LayoutTestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/questions/$sectionId': typeof LayoutQuestionsSectionIdRoute
  '/_layout/train/$sectionId': typeof LayoutTrainSectionIdRoute
  '/_layout/questions/': typeof LayoutQuestionsIndexRoute
  '/_layout/test/': typeof LayoutTestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/questions/$sectionId'
    | '/train/$sectionId'
    | '/questions/'
    | '/test/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/questions/$sectionId'
    | '/train/$sectionId'
    | '/questions'
    | '/test'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/questions/$sectionId'
    | '/_layout/train/$sectionId'
    | '/_layout/questions/'
    | '/_layout/test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/test/': {
      id: '/_layout/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof LayoutTestIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/questions/': {
      id: '/_layout/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof LayoutQuestionsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/train/$sectionId': {
      id: '/_layout/train/$sectionId'
      path: '/train/$sectionId'
      fullPath: '/train/$sectionId'
      preLoaderRoute: typeof LayoutTrainSectionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/questions/$sectionId': {
      id: '/_layout/questions/$sectionId'
      path: '/questions/$sectionId'
      fullPath: '/questions/$sectionId'
      preLoaderRoute: typeof LayoutQuestionsSectionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutQuestionsSectionIdRoute: typeof LayoutQuestionsSectionIdRoute
  LayoutTrainSectionIdRoute: typeof LayoutTrainSectionIdRoute
  LayoutQuestionsIndexRoute: typeof LayoutQuestionsIndexRoute
  LayoutTestIndexRoute: typeof LayoutTestIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutQuestionsSectionIdRoute: LayoutQuestionsSectionIdRoute,
  LayoutTrainSectionIdRoute: LayoutTrainSectionIdRoute,
  LayoutQuestionsIndexRoute: LayoutQuestionsIndexRoute,
  LayoutTestIndexRoute: LayoutTestIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
