/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTestIndexRouteImport } from './routes/_layout/test/index'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as LayoutTrainSectionIdRouteImport } from './routes/_layout/train/$sectionId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTestIndexRoute = LayoutTestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTrainSectionIdRoute = LayoutTrainSectionIdRouteImport.update({
  id: '/train/$sectionId',
  path: '/train/$sectionId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/train/$sectionId': typeof LayoutTrainSectionIdRoute
  '/settings/': typeof LayoutSettingsIndexRoute
  '/test/': typeof LayoutTestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/train/$sectionId': typeof LayoutTrainSectionIdRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/test': typeof LayoutTestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/train/$sectionId': typeof LayoutTrainSectionIdRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/test/': typeof LayoutTestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/train/$sectionId' | '/settings/' | '/test/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/train/$sectionId' | '/settings' | '/test'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/train/$sectionId'
    | '/_layout/settings/'
    | '/_layout/test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/test/': {
      id: '/_layout/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof LayoutTestIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/train/$sectionId': {
      id: '/_layout/train/$sectionId'
      path: '/train/$sectionId'
      fullPath: '/train/$sectionId'
      preLoaderRoute: typeof LayoutTrainSectionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutTrainSectionIdRoute: typeof LayoutTrainSectionIdRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutTestIndexRoute: typeof LayoutTestIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutTrainSectionIdRoute: LayoutTrainSectionIdRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutTestIndexRoute: LayoutTestIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
